name: Build & Release oicdb repository
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set release tag as env var
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Print release tag
        run: echo ${{ steps.tag.outputs.version }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: scripts
          dev: no

      - name: Run oicdb build script
        run: ./testAndBuild.php "${{ env.RELEASE_VERSION }}"
        working-directory: scripts

      - name: Upload oicdb.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: oicdb-${{ env.RELEASE_VERSION }}.json
          path: build/oicdb-${{ env.RELEASE_VERSION }}.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically build oicdb-${{ env.RELEASE_VERSION }}.json
          file_pattern: "build/oicdb-${{ env.RELEASE_VERSION }}.json build/oicdb-latest.json"

      - name: Attach oicdb repository to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/oicdb-${{ env.RELEASE_VERSION }}.json
          tag_name: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}